# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1895QROUkueIZcUuqkwg9d9PW35xKtGmy
"""

def lower_triangular(n):
    for i in range(1, n + 1):
        print('*' * i)
    print()

def upper_triangular(n):
    for i in range(n, 0, -1):
        print('*' * i)
    print()

def pyramid(n):
    for i in range(n):
        print(' ' * (n - i - 1) + '*' * (2 * i + 1))
    print()

n = 5

print("Lower Triangular Pattern:")
lower_triangular(n)

print("Upper Triangular Pattern:")
upper_triangular(n)

print("Pyramid Pattern:")
pyramid(n)